version: '3.3'
services:
  # copied from https://github.com/calvinlfer/compose-cassandra-cluster/blob/master/docker-compose.yml
  cassandra-seed-id-service:
    container_name: cassandra-seed-id-service
    image: cassandra:3.11.0
    ports:
      - 9042:9042   # Native transport
      - 9160:9160   # Thrift clients
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    logging:
      driver: none

  cassandra-node-1-id-service:
    container_name: cassandra-node-1-id-service
    image: cassandra:3.11.0
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 40 && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=cassandra-seed-id-service
    depends_on:
      - cassandra-seed-id-service
  #    logging:
  #      driver: none

  # you cannot have multiple nodes join the cluster at the same time when
  # cassandra.consistent.rangemovement is true so we further delay it to give it time to stabilize
  cassandra-node-2-id-service:
    container_name: cassandra-node-2-id-service
    image: cassandra:3.11.0
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 40 && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=cassandra-seed-id-service
    depends_on:
      - cassandra-seed-id-service
  #    logging:
  #      driver: none

  # This cassandra only helps to load the schema, thus keyspace and it's different tables
  cassandra-load-schema-node-id-service:
    container_name: cassandra-load-schema-node-id-service
    image: cassandra:3.11.0
    depends_on:
      - cassandra-seed-id-service
    volumes:
      - ./src/main/resources/db:/db
    command: /bin/bash -c  "sleep 60 && ls db/ && echo importing schema && cqlsh cassandra-seed-id-service -f db/schemaOverview.cql "

  zookeeper-id-service:
    container_name: zookeeper-id-service
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    logging:
      driver: none

  kafka-id-service:
    container_name: kafka-id-service
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-id-service:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper-id-service
#    logging:
#      driver: none
