version: '3.3'
services:
  # copied from https://github.com/calvinlfer/compose-cassandra-cluster/blob/master/docker-compose.yml
  cassandra-seed-id-service:
    container_name: cassandra-seed-id-service
    image: cassandra:4.0.7
    ports:
      - 9042:9042   # Native transport
      - 9160:9160   # Thrift clients
    volumes:
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    logging:
      driver: none

  cassandra-node-1-id-service:
    container_name: cassandra-node-1-id-service
    image: cassandra:4.0.7
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    volumes:
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
    environment:
      - CASSANDRA_SEEDS=cassandra-seed-id-service
    depends_on:
      - cassandra-seed-id-service
    logging:
      driver: none

  # This cassandra only helps to load the schema, thus keyspace and it's different tables
  cassandra-load-schema-node-id-service:
    container_name: cassandra-load-schema-node-id-service
    image: cassandra:4.0.7
    depends_on:
      - cassandra-seed-id-service
    volumes:
      - ./src/main/resources/db:/db
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
    command: /bin/bash -c  "sleep 50 && ls db/ && echo importing schema && cqlsh cassandra-seed-id-service -f db/schemaOverview.cql "

  zookeeper-id-service:
    container_name: zookeeper-id-service
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    tmpfs: "/datalog"
    logging:
      driver: none

  kafka-id-service:
    container_name: kafka-id-service
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-id-service:2181
      - KAFKA_CFG_LISTENERS=INSIDE://:29092,OUTSIDE://127.0.0.1:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INSIDE://:29092,OUTSIDE://127.0.0.1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INSIDE
    depends_on:
      - zookeeper-id-service
    logging:
      driver: none
